version: '3'

services: 
  supermarket_db:
    container_name: supermarket_db
    restart: always
    image: postgres
    environment: 
      POSTGRES_USER: supermarket
      POSTGRES_PASSWORD: 2021
      POSTGRES_DB: supermarket_db
    ports:
      - 5432:5432
    volumes:
      - ./supermarket_db:/var/lib/postgresql/data
  supermarket_ms:
    restart: always
    container_name: supermarket_ms
    ports:
      - 4000:4000
    build: ./supermarket_ms
    environment: 
      DB_HOST: supermarket_db
      DB_PORT: 5432
      DB_USER: supermarket
      DB_PASSWORD: 2021
      DB_NAME: supermarket_db
      URL: 0.0.0.0:4000
    depends_on: 
      - supermarket_db
    links: 
      - supermarket_db
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: tutor@univalle.com
      PGADMIN_DEFAULT_PASSWORD: albaricoque
    volumes:
      - ./supermarket_db:/var/lib/postgresql/data
    ports:
      - '5050:80'
